apiVersion: apps:v1
kind: Deployment
metadata:
  name: customer-studentdb
  labels:
    app: customer-studentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-studentdb
  template:
    metadata:
      name: customer-studentdb
      labels:
        app: customer-studentdb
    spec:
      containers:
      - name: customer-studentdb
        image: prashantojha01/customer:v1
        ports:
          - containerPort: 8080
            name: mysql-deploy
        env: 
          - name: DB_HOSTNAME
              value: 192.168.145.244
          - name: DB_PORT
              value: "3306"
          - name: DB_NAME 
              value: "studentdb"
          - name: DB_USERNAME
              value: "root"
          - name: DB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mysql-password
                    key: db-password 
